version: '3.9'

services:
  web:
    build:
      context: ./myproject
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./myproject:/app
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
